server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/machines
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: machines-api
