-- Insert sample subcategories
INSERT INTO subcategories (id, created_at, updated_at, deleted_at, name, category_id)
VALUES (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Ръчни инструменти разни',
        (SELECT id FROM categories WHERE name = 'Разни')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Металообработващи свредила, фрезери, метчици и др',
        (SELECT id FROM categories WHERE name = 'Разни')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Дървообработващи бургии, фрезери, дискове и др.',
        (SELECT id FROM categories WHERE name = 'Разни')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Металообработващи машини',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Дървообработващи машини',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Лазерни машини',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Машини с ЦПУ',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Плазмено рязане',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Текстилни машини',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ПВЦ и АЛ дограма',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Пластмаса',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Компресори и оборудване',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Др. Промишлени машини',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Резервни части машини',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Горскостопански машини',
        (SELECT id FROM categories WHERE name = 'Промишлени производствени машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Ръчни инструменти',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Давам техника под наем',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Довършителни дейности',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'За монтаж и гипскартон',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Машини ВиК',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Шлайф машини',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Бояджийска техника',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Мазилки и замазки',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Багери',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Мини багери',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Мини челни товарали',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Комбинирани багери',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Кранове, хаспели',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Пътностроителна техника',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Валяци',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Други строителни машини',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Резервни части машини',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Крепежни елементи',
        (SELECT id FROM categories WHERE name = 'Строителни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Дребна строителна техника',
        (SELECT id FROM categories WHERE name = 'Дребна строителна техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ОВК и ВиК',
        (SELECT id FROM categories WHERE name = 'ОВК и ВиК')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Укрепителни системи',
        (SELECT id FROM categories WHERE name = 'Укрепителни системи')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Кранове',
        (SELECT id FROM categories WHERE name = 'Подемни съоръжения')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Вишки',
        (SELECT id FROM categories WHERE name = 'Подемни съоръжения')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Електрокари',
        (SELECT id FROM categories WHERE name = 'Подемни съоръжения')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Пневматични системи',
        (SELECT id FROM categories WHERE name = 'Подемни съоръжения')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Платформи',
        (SELECT id FROM categories WHERE name = 'Подемни съоръжения')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Друга подемна техника',
        (SELECT id FROM categories WHERE name = 'Подемни съоръжения')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Резервни части машини',
        (SELECT id FROM categories WHERE name = 'Подемни съоръжения')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Печатарски машини',
        (SELECT id FROM categories WHERE name = 'Печатарски машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Складово оборудване',
        (SELECT id FROM categories WHERE name = 'Складово оборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Машини за ХВП',
        (SELECT id FROM categories WHERE name = 'Машини за ХВП')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Автосервизно оборудване',
        (SELECT id FROM categories WHERE name = 'Автосервизно оборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Машини за ХВП',
        (SELECT id FROM categories WHERE name = 'Машини за ХВП')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Трактори',
        (SELECT id FROM categories WHERE name = 'Селскостопанска техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Мотокултиватори',
        (SELECT id FROM categories WHERE name = 'Селскостопанска техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Резервни части машини селстостопанство',
        (SELECT id FROM categories WHERE name = 'Селскостопанска техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Комбайни',
        (SELECT id FROM categories WHERE name = 'Селскостопанска техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Други селскостопански машини',
        (SELECT id FROM categories WHERE name = 'Селскостопанска техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Климатична техника',
        (SELECT id FROM categories WHERE name = 'Климатична техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Лабораторно оборудване',
        (SELECT id FROM categories WHERE name = 'Лабораторно оборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Медицинско оборудване',
        (SELECT id FROM categories WHERE name = 'Медицинско оборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Други машини',
        (SELECT id FROM categories WHERE name = 'Други машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Камиони',
        (SELECT id FROM categories WHERE name = 'Транспортни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Фургони',
        (SELECT id FROM categories WHERE name = 'Транспортни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Микробуси',
        (SELECT id FROM categories WHERE name = 'Транспортни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'ТПолуремаркета',
        (SELECT id FROM categories WHERE name = 'Транспортни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Платформи',
        (SELECT id FROM categories WHERE name = 'Транспортни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Други транспортни машини',
        (SELECT id FROM categories WHERE name = 'Транспортни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Резервни части машини',
        (SELECT id FROM categories WHERE name = 'Транспортни машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Комуникационна техника',
        (SELECT id FROM categories WHERE name = 'Комуникационна техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Оптична техника',
        (SELECT id FROM categories WHERE name = 'Оптична техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Почистваща техника',
        (SELECT id FROM categories WHERE name = 'Почистваща техника')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Агрегати',
        (SELECT id FROM categories WHERE name = 'Електрооборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Заваръчна техника',
        (SELECT id FROM categories WHERE name = 'Електрооборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Трансформатори и телефери',
        (SELECT id FROM categories WHERE name = 'Електрооборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Електродвигатели',
        (SELECT id FROM categories WHERE name = 'Електрооборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Резервни части и оборудване',
        (SELECT id FROM categories WHERE name = 'Електрооборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Друго електооборудване',
        (SELECT id FROM categories WHERE name = 'Електрооборудване')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Вносители на машини',
        (SELECT id FROM categories WHERE name = 'Вносители на машини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Раз. части и консумативи',
        (SELECT id FROM categories WHERE name = 'Раз. части и консумативи')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Техническа документация',
        (SELECT id FROM categories WHERE name = 'Техническа документация')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Суровини',
        (SELECT id FROM categories WHERE name = 'Суровини')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Материали',
        (SELECT id FROM categories WHERE name = 'Материали')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Услуги металообработване',
        (SELECT id FROM categories WHERE name = 'Предлагам услуги')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Услуги дървообработване',
        (SELECT id FROM categories WHERE name = 'Предлагам услуги')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Други на ишлеме',
        (SELECT id FROM categories WHERE name = 'Предлагам услуги')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Изкопи',
        (SELECT id FROM categories WHERE name = 'Търся подизпълнителни услуги')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Транспортни услуги',
        (SELECT id FROM categories WHERE name = 'Търся подизпълнителни услуги')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Други услуги',
        (SELECT id FROM categories WHERE name = 'Търся подизпълнителни услуги')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Мотокари и Електрокари под наем',
        (SELECT id FROM categories WHERE name = 'Давам техника под наем')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Вишки и кранове под наем',
        (SELECT id FROM categories WHERE name = 'Давам техника под наем')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Багери и минибагери под наем',
        (SELECT id FROM categories WHERE name = 'Давам техника под наем')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Скелета под наем',
        (SELECT id FROM categories WHERE name = 'Давам техника под наем')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Подпори под наем',
        (SELECT id FROM categories WHERE name = 'Давам техника под наем')),
       (uuid_generate_v4(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'Друга техника под наем',
        (SELECT id FROM categories WHERE name = 'Давам техника под наем'));