-- V12__Insert_Sample_Offers_and_Offer_Pictures.sql

-- Insert sample offer data
INSERT INTO offers (id, created_at, updated_at, deleted_at, title, phone_number, description, website_url, price,
                    is_bulgarian, auto_update, offer_state, offer_sale_type, offer_type, city_id, subcategory_id,
                    main_picture_id, owner_id, manufacture_year, model, power_supply_voltage, fuel_type, horse_power,
                    consumption, output_power, productivity, capacity, min_revolutions, nominal_revolutions,
                    max_revolutions, dimensions, own_weight, work_moves)
VALUES (uuid_generate_v4(),
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        NULL,
        'Example Offer 1',
        '+1234567890',
        'This is a detailed description of Example Offer 1.',
        'https://example.com',
        1500.00,
        TRUE,
        FALSE,
        'USED',
        'SALE',
        'VIP',
        (SELECT id FROM cities WHERE name = 'Los Angeles'),
        (SELECT id FROM subcategories WHERE name = 'Fiction'),
        (SELECT id FROM files WHERE name = '041ac8f3-4e17-409c-a3b1-1b44452cc869.jpg'),
        (SELECT id FROM users WHERE name = 'Admin'),
        2022,
        'Model X',
        220.00,
        'Electric',
        120.00,
        'Low consumption',
        150.00,
        'High productivity',
        75.00,
        1500.00,
        2500.00,
        3000.00,
        '120x60x80 cm',
        500.00,
        'Works well');

-- Insert sample offer pictures
INSERT INTO offers_pictures (offer_id, file_id)
VALUES ((SELECT id FROM offers WHERE title = 'Example Offer 1'),
        (SELECT id FROM files WHERE name = '041ac8f3-4e17-409c-a3b1-1b44452cc869.jpg')),
       ((SELECT id FROM offers WHERE title = 'Example Offer 1'),
        (SELECT id FROM files WHERE name = '1f92af23-4c73-4a50-bcf1-bebb5951b6dd.jpg'));

-- Insert duplicate sample offer data with updated titles
INSERT INTO offers (id, created_at, updated_at, deleted_at, title, phone_number, description, website_url, price,
                    is_bulgarian, auto_update, offer_state, offer_sale_type, offer_type, city_id, subcategory_id,
                    main_picture_id, owner_id, manufacture_year, model, power_supply_voltage, fuel_type, horse_power,
                    consumption, output_power, productivity, capacity, min_revolutions, nominal_revolutions,
                    max_revolutions, dimensions, own_weight, work_moves)
VALUES (uuid_generate_v4(),
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        NULL,
        'Example Offer 2',
        '+1234567891',
        'This is a detailed description of Example Offer 2.',
        'https://example.com',
        1500.00,
        TRUE,
        FALSE,
        'NEW_IMPORTATION',
        'SERVICES',
        'TOP',
        (SELECT id FROM cities WHERE name = 'Los Angeles'),
        (SELECT id FROM subcategories WHERE name = 'Fiction'),
        (SELECT id FROM files WHERE name = '1f92af23-4c73-4a50-bcf1-bebb5951b6dd.jpg'),
        (SELECT id FROM users WHERE name = 'Regular'),
        2022,
        'Model X',
        220.00,
        'Electric',
        120.00,
        'Low consumption',
        150.00,
        'High productivity',
        75.00,
        1500.00,
        2500.00,
        3000.00,
        '120x60x80 cm',
        500.00,
        'Works well');

-- Insert duplicate offer pictures for the new offer
INSERT INTO offers_pictures (offer_id, file_id)
VALUES ((SELECT id FROM offers WHERE title = 'Example Offer 2'),
        (SELECT id FROM files WHERE name = '1f92af23-4c73-4a50-bcf1-bebb5951b6dd.jpg')),
       ((SELECT id FROM offers WHERE title = 'Example Offer 2'),
        (SELECT id FROM files WHERE name = '041ac8f3-4e17-409c-a3b1-1b44452cc869.jpg'));

-- Insert duplicate sample offer data with updated titles
INSERT INTO offers (id, created_at, updated_at, deleted_at, title, phone_number, description, website_url, price,
                    is_bulgarian, auto_update, offer_state, offer_sale_type, offer_type, city_id, subcategory_id,
                    main_picture_id, owner_id, manufacture_year, model, power_supply_voltage, fuel_type, horse_power,
                    consumption, output_power, productivity, capacity, min_revolutions, nominal_revolutions,
                    max_revolutions, dimensions, own_weight, work_moves)
VALUES (uuid_generate_v4(),
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        NULL,
        'Example Offer 3',
        '+1234567892',
        'This is a detailed description of Example Offer 3.',
        'https://example.com',
        1500.00,
        TRUE,
        FALSE,
        'NEW_IMPORTATION',
        'SERVICES',
        'TOP',
        (SELECT id FROM cities WHERE name = 'Los Angeles'),
        (SELECT id FROM subcategories WHERE name = 'Fiction'),
        (SELECT id FROM files WHERE name = '041ac8f3-4e17-409c-a3b1-1b44452cc869.jpg'),
        (SELECT id FROM users WHERE name = 'Regular'),
        2022,
        'Model X',
        220.00,
        'Electric',
        120.00,
        'Low consumption',
        150.00,
        'High productivity',
        75.00,
        1500.00,
        2500.00,
        3000.00,
        '120x60x80 cm',
        500.00,
        'Works well');

-- Insert duplicate offer pictures for the new offer
INSERT INTO offers_pictures (offer_id, file_id)
VALUES ((SELECT id FROM offers WHERE title = 'Example Offer 3'),
        (SELECT id FROM files WHERE name = '041ac8f3-4e17-409c-a3b1-1b44452cc869.jpg')),
       ((SELECT id FROM offers WHERE title = 'Example Offer 3'),
        (SELECT id FROM files WHERE name = '1f92af23-4c73-4a50-bcf1-bebb5951b6dd.jpg'));

-- Insert duplicate sample offer data with updated titles
INSERT INTO offers (id, created_at, updated_at, deleted_at, title, phone_number, description, website_url, price,
                    is_bulgarian, auto_update, offer_state, offer_sale_type, offer_type, city_id, subcategory_id,
                    main_picture_id, owner_id, manufacture_year, model, power_supply_voltage, fuel_type, horse_power,
                    consumption, output_power, productivity, capacity, min_revolutions, nominal_revolutions,
                    max_revolutions, dimensions, own_weight, work_moves)
VALUES (uuid_generate_v4(),
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        NULL,
        'Example Offer 4',
        '+1234567893',
        'This is a detailed description of Example Offer 4.',
        'https://example.com',
        1500.00,
        TRUE,
        FALSE,
        'NEW_IMPORTATION',
        'SERVICES',
        'TOP',
        (SELECT id FROM cities WHERE name = 'Los Angeles'),
        (SELECT id FROM subcategories WHERE name = 'Fiction'),
        (SELECT id FROM files WHERE name = '041ac8f3-4e17-409c-a3b1-1b44452cc869.jpg'),
        (SELECT id FROM users WHERE name = 'Regular'),
        2022,
        'Model X',
        220.00,
        'Electric',
        120.00,
        'Low consumption',
        150.00,
        'High productivity',
        75.00,
        1500.00,
        2500.00,
        3000.00,
        '120x60x80 cm',
        500.00,
        'Works well');

-- Insert duplicate offer pictures for the new offer
INSERT INTO offers_pictures (offer_id, file_id)
VALUES ((SELECT id FROM offers WHERE title = 'Example Offer 4'),
        (SELECT id FROM files WHERE name = '041ac8f3-4e17-409c-a3b1-1b44452cc869.jpg')),
       ((SELECT id FROM offers WHERE title = 'Example Offer 4'),
        (SELECT id FROM files WHERE name = '1f92af23-4c73-4a50-bcf1-bebb5951b6dd.jpg'));
